apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.backend.service.port }}
      targetPort: 8080
      nodePort: 32323
  selector:
    app: backend

