apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: {{ .Values.frontend.image }}
          ports:
            - containerPort: 5173
              #          env:
              #            - name: VITE_BACKEND_URL
              #              value: "http://localhost:{{ .Values.backend.service.port }}"
              #            - name: VITE_API_URL
              #              value: "http://backend:5000"

