pipeline {
    agent {
        label 'minikube'  // Runs on an agent labeled 'minikube'
    }
    parameters {
        choice(name: 'action', choices: ['apply', 'destroy'], description: 'Select action to perform')
    }
    
    environment {
        GIT_REPO_URL = 'https://github.com/muthu-vinayagam/wanderlust.git' // Replace with your repository URL
        GIT_BRANCH = 'main' // Replace with your branch name
        GIT_CREDENTIALS_ID = 'git-secret' // Replace with the ID of your Jenkins credentials
    }
    stages {
        stage('Clean Workspace') {
            steps {
                echo 'Cleaning the workspace...'
                deleteDir()  // Cleans the workspace
            }
        }
        
        stage('Clone Repository') {
            steps {
                echo 'Cloning the repository...'
                checkout([
                    $class: 'GitSCM',
                    branches: [[name: env.GIT_BRANCH]],
                    doGenerateSubmoduleConfigurations: false,
                    extensions: [],
                    submoduleCfg: [],
                    userRemoteConfigs: [[
                        url: env.GIT_REPO_URL,
                        credentialsId: env.GIT_CREDENTIALS_ID
                    ]]
                ])
            }
        }

        stage('Terraform Init') {
            steps {
                dir('updateterraformm') {
                 sh 'terraform init'
                }
            }
        }

        stage('Terraform Plan') {
            steps {
                dir('updateterraformm') {
                 sh 'terraform plan -out=tfplan'
                }
            }
        }

        stage('Apply Resources') {
            when {
                expression { params.action == 'apply' }
            }
            steps {
                dir('updateterraformm') {
                echo 'Applying resources...'
                sh 'terraform apply -auto-approve tfplan'
                }
            }
        }
        
        stage('Destroy Resources') {
            when {
                expression { params.action == 'destroy' }
            }
            steps {
                dir('updateterraformm') {
                echo 'Destroying resources...'
                sh 'terraform destroy -auto-approve'
                }
            }
        }
    }
}
